# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "ER-Non-Plus-CLI-3-DEV"
client_id = "bb09fda1fda48461e7aea894f9d2edca"
application_url = "https://lecture-champion-jeans-anaheim.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_discounts,read_fulfillments,read_gift_cards,read_orders,read_themes,unauthenticated_write_checkouts,write_customers,write_discounts,write_draft_orders,write_gift_cards,write_orders,write_products,write_script_tags"

[auth]
redirect_urls = [
  "https://lecture-champion-jeans-anaheim.trycloudflare.com/auth/callback",
  "https://lecture-champion-jeans-anaheim.trycloudflare.com/auth/shopify/callback",
  "https://lecture-champion-jeans-anaheim.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[app_proxy]
url = "https://lecture-champion-jeans-anaheim.trycloudflare.com"
subpath = "ez"
prefix = "apps"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-a7607a1f.myshopify.com"
